### ISSUE TITLE
Export 'allPlugins' from main module

### ISSUE THREAD

**Issue by voodooattack** [esnext/esnext#104]
Currently `convert()` expects an array of plugins, not plugin names. It is not usable if we can't access the plugins and selectively pass them.

**Comment by alangpierce** [comment]
Agreed that it seems like the API is just unusable right now. I'm also running into this when trying to implement https://github.com/decaffeinate/decaffeinate/issues/407 . I want decaffeinate to specify everything but the modules.commonjs plugin, but it looks like there's no way to do that.

@eventualbuddha do you know what you had in mind here? IMO it's a little weird for a config object to have full `Plugin` objects, but I guess one possibly nice thing is it allows people to pass in plugins other than the built-in ones. Some possible changes to fix this:
* Keep the API the same but expose `allPlugins` (as suggested by @voodooattack ).
* Instead of `plugins` being an array of plugin objects, make it an array of strings. Ideally we'd also export the names of all plugins to better to support use cases like mine.
* Add a few options for the common use cases, with precedence rules. For example, `includedPluginNames` and `excludedPluginNames` could be used to run just one or two plugins or all but one or two. This is more friendly with JSON config files.

The first option seems like a pretty easy change and works for my use case (I'd just call `filter` in JS code), so I'll put up a PR for that.
