### ISSUE TITLE
Separation from babel?

### ISSUE THREAD

**Issue by ustun** [esnext/esnext#73]
I see that this project has been rebooted. Could you provide some context for those not familiar?

**Comment by eventualbuddha** [comment]
I should have provided some more context. This project isn't being rebooted in a way that competes with babel, as it did before. I see it as a compliment to babel now, since what it does now is effectively the reverse of what it did before: convert legacy JavaScript to next-generation JavaScript instead of the reverse.

The idea is this: you have a project written using old-style JavaScript features, like `var` instead of `const` and `let`, or `function` instead of `=>` for callbacks etc, or using CommonJS instead of the new module syntax. You'd like to modernize your source code, but doing so is tedious. This project, rebooted, aims to help with that. It is something you could run on your code periodically to help you update your actual source code, then use babel on that source code to run it in legacy environments.

Does that make sense?
